config/routes.rb
Rails.application.routes.draw do

  resources :documents do
    resources :revisions do
      resources :compares
    end
    collection {get :restore}
  end
  root "documents#index"
end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :revisions, dependent: :destroy
  # def test
  #   binding.pry
  # end
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  belongs_to :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/confliction.rb
module Confliction
  def recoginze_conflict document, description
    result = ""
    conflict = false
    description.split("\n").each do |line|
      match_line = /(.*){(.*)}(.*)/.match(line)
      binding.pry
      if match_line
        result.concat(match_line[1]).concat("\n")
        line_change = /\"(.*)\" >> \"(.*)\"/.match(match_line[2])
        line_add = /[\+]\"(.*)\"/.match(match_line[2])
        line_remove = /[\-]\"(.*)\"/.match(match_line[2])
        if line_change
          result.concat("<<<<< HEAD \n").concat(line_change[1]).concat("\n =====\n").concat(line_change[2]).concat("\n >>>>> your change\n")
          conflict = true
        elsif line_add
          result.concat(line_add[1])
        elsif line_remove
          result.concat(line_remove[1])
        end
        result.concat(match_line[3])
      else
        result.concat(line)
      end
    end

    if conflict == true
      description = result
      result = result.gsub("\\r","\r").gsub("\\n","\n")
      document.update_attributes(lastest_revision: document.revisions.last.version_id)
      flash[:warning] = "Conflicted"
      render :edit
    else
      result = result.gsub("\\r","\r").gsub("\\n","")
      document.update_attributes(description: result)
      version_id = document.revisions.last.version_id
      new_version_id = version_id + 1
      create_revision(revision_params, new_version_id, params[:id])
      document.update_attributes(lastest_revision: Revision.last.version_id)
      redirect_to document
      flash[:warning] = "Auto merged"
    end
  end
end

app/controllers/concerns/restore_revision.rb
module RestoreRevision
  def restore_to restore_revision, document
    document.update_attributes(title: restore_revision.title,
      description: restore_revision.description, lastest_revision: document.lastest_revision + 1)
    Revision.create(title: restore_revision.title, description: restore_revision.description,
       document_id: params[:id], version_id: document.revisions.last.version_id.to_i + 1)
    redirect_to document_revisions_path(document.id)
    flash[:warning] = "Document was restored to the same version: #{@restore_revision.version_id}"
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include Confliction
  include RestoreRevision
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  def index
    @documents = Document.all
  end

  def show
  end

  def new
    @document = Document.new
  end

  def edit
    $document = Document.find_by(id: params[:id])
    @data = {document: @document}
  end

  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
        create_revision(revision_params, 1, @document.id)
        @document.update_attributes(lastest_revision: @document.revisions.last.version_id)
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # @document.test
    unless params[:ver_restore].present?
      if (params[:document][:lastest_revision].to_i + 1) > @document.revisions.last.version_id
        respond_to do |format|
          if @document.update(document_params)
            format.html { redirect_to @document, notice: 'Document was successfully updated.' }
            format.json { render :show, status: :ok, location: @document }
            new_version_id = @document.revisions.last.version_id + 1
            create_revision(revision_params, new_version_id, params[:id])
            @document.update_attributes(lastest_revision: @document.revisions.last.version_id)
          else
            format.html { render :edit }
            format.json { render json: @document.errors, status: :unprocessable_entity }
          end
        end
      else
        if @document.description.strip != params[:document][:description].strip
          @document.description = Differ.diff_by_line(params[:document][:description], @document.description)
          recoginze_conflict @document, @document.description
        else
          flash[:warning] = "Auto merged"
          redirect_to @document
        end
      end
    else
      @restore_revision = Revision.find_by(id: params[:ver_restore])
      restore_to @restore_revision, @document
    end
  end

  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:title, :description, :lastest_revision)
    end

    def revision_params
      params.require(:document).permit(:title, :description)
    end

    def create_revision params, version_id, document_id
      @revision = Revision.new(params)
      @revision.save
      @revision.update_attributes(document_id: document_id, version_id: version_id)
    end
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  def index
    @document = Document.find_by(id: params[:document_id])
    @revisions = @document.revisions.order(id: :desc)
    @current_revision = @document.revisions.find_by(version_id: params[:current_revision])
    @previous_revision = @document.revisions.order(:version_id).
      limit(params[:current_revision]).last(2).first
  end

  def show
    @compare_with_previous = params[:compare_with_previous]
    if @compare_with_previous == "true"
      @document = Document.find_by(id: params[:document_id])
      @current_revision = @document.revisions.find_by(version_id: params[:id])
      @previous_revision = @document.revisions.order(:version_id).
        limit(params[:id]).last(2).first
      if @current_revision.version_id > 1
        @change_title = Differ.diff_by_line(@previous_revision.title,
          @current_revision.title).format_as(:html)

        @change_description = Differ.diff_by_line(@current_revision.description,
          @previous_revision.description).format_as(:html)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compares_helper.rb
module ComparesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/compares/index.html.slim
- unless @change_title
  em
    | It the first revision, no previous version to compare title
- else
  - if @change_title == '<div class="diff"></div>'
    h6
      | Title no change:
    = @current_revision.title
  - else
    h6
      | Title was changed
    = @change_title.html_safe

- unless @change_description
  em
    br
    | It the first revision, no previous version to compare description
- else
  - if @change_description == '<div class="diff"></div>'
    h6
      | Description no change:
    = @current_revision.description
  - else
    h6
      | Description was changed
    = @change_description.html_safe

app/views/documents/_form.html.slim
.ui.form
  = form_for(@document) do |f|
    - if @document.errors.any?
      #error_explanation
        h2
          = pluralize(@document.errors.count, "error")
          |  prohibited this document from being saved:
        ul
          - @document.errors.full_messages.each do |message|
            li
              = message
    = f.hidden_field :lastest_revision, value: @document.lastest_revision
    .field
      = f.label :title
      br
      = f.text_field :title
    .field
      = f.label :description
      br
      = f.text_area :description
    = f.submit "Submit", class: "ui blue submit button"

app/views/documents/edit.html.slim
h1
  | Editing Document
= render 'form'
= link_to 'Show', @document
|  |
= link_to 'Back', documents_path

app/views/documents/index.html.slim
#index
  h1
    | Listing Documents
  table.ui.celled.striped.table
    thead
      tr
        th.title
          | Title
        th[colspan="4"]
    tbody
      - @documents.order("id desc").each do |document|
        tr
          td.title
            = document.title
          td.action
            = link_to 'Show', document, class: "ui blue submit button"
          td.action
            = link_to 'Edit', edit_document_path(document), class: "ui blue submit button"
          td.action
            = link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui red submit button"
          td.action
            = link_to "revisions", document_revisions_path(document.id), class: "ui blue submit button"
  br
  = link_to 'New Document', new_document_path, class: "ui blue submit button"

app/views/documents/new.html.slim
h1
  |New Document

= render 'form'

= link_to 'Back', documents_path

app/views/documents/show.html.slim
#show
  #content
    p
      strong
        | Title:
      = @document.title
    p
      strong
        | Description:
      = simple_format @document.description

<br>
= link_to 'Edit', edit_document_path(@document), class: "ui button blue"
= link_to 'Back', documents_path, class: "btn-black"

app/views/layouts/_message.html.slim
- flash.each do |name, msg|
  - type = case name
  - when "success"
    - "positive"
  - when "error"
    - "negative"
  - else
    - "teal"

  div class="ui #{type} message"
    i class="close icon"
    .header
      = msg

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RevisionControl
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render "shared/header"
    #container
      = render "layouts/message"
      = yield
    = render "shared/footer"

app/views/revisions/index.html.slim
#revisions
  table.ui.celled.striped.table
    thead
      tr
        th.version
          | Revision
        th.title
          | Title
        th.description
          | Description
        th[colspan="2"]
    tbody
    - @revisions.each do |revision|
      tr
        td.version
          = revision.version_id
        td.title
          = revision.title
        td.description
          = simple_format revision.description
        td.action
          - if revision != @revisions.last
            = link_to "diff", document_revision_path(params[:document_id], revision.version_id,
              compare_with_previous: true), class: "ui button blue"
        td.action
          - unless revision == @revisions.first
            = link_to document_path(@document, action: :update, ver_restore: revision.id),
              class: "ui button orange", method: :patch do
              = t "restore"
  = link_to "Back", documents_path

app/views/revisions/show.html.slim
- if @compare_with_previous == "true"
  - unless @change_title
    em
      | It the first revision, no previous version to compare title
  - else
    - if @change_title == @document.title
      h5
        | Title no change:
      = @current_revision.title
    - else
      h5
        | Title was changed
      = @change_title.html_safe

  - unless @change_description
    em
      br
      | It the first revision, no previous version to compare description
  - else
    - if @change_description.strip == @document.description.strip
      h5
        | Description no change:
      = @current_revision.description
    - else
      h5
        | Description was changed
      = simple_format @change_description
- binding.pry

app/views/shared/_footer.html.slim
#footer
  h5.test
    | Created by Duyet Nguyen

app/views/shared/_header.html.slim
#header
  h1
    = link_to "Revision controll", root_path, class: "header-home"